### ISSUE TITLE
Location of the files

### ISSUE THREAD

**Issue by laictype** [chrissimpkins/fontname.py#7]
Hello,
The fontmake.py files should always be stored in the folder where the font files are or there is a way to install "globally" on a computer?

Thanks,
Maciej

**Comment by chrissimpkins** [comment]
Hi Maciej!

What operating system are you using? It is possible to define this script so that it runs globally on your command line, but the approach differs by OS

**Comment by laictype** [comment]
Thank you for your answer!
I'm on Big Sur 11.3 (20E232)

**Comment by chrissimpkins** [comment]
> I'm on Big Sur 11.3 (20E232)

I am on macOS too. The way that I approach it is to add scripts (shell, Python) to a `scripts` directory under my home directory, and then add that directory to my system PATH.  Here is an example of instructions to update your PATH on Big Sur:

https://wpbeaches.com/how-to-add-to-the-shell-path-in-macos-using-terminal/

My approach is the "permanent" approach in that article.  I edit the PATH in the `.zshrc` configuration file with the following line:

```zshrc
export PATH="/Users/chris/scripts:$PATH"
```

Take care to confirm that your paths are correct when you do this if you are not familiar with PATH editing.  It is possible to interfere with access to system executables on your system if you do something like forget to add the `$PATH` element in the line (this appends or prepends the existing PATH defintion based on the location where you place it in the string, this is how you define priority of executables that have the same name - if it points to a same name file that is first in order it takes precedence over one that is found in a dir path later in the PATH string).

Keep the fontname.py script in the top level of the directory that you add to your path.  Make sure to run the `source ~/.zshrc` step after you edit the .zshrc file and then you can run the script here with the following command on your command line from any working directory:

```
fontname.py [NEW FONT FAMILY NAME] [FONT PATH 1] <FONT PATH ...>
```

Note that you need to install the `fonttools` Python package in order to do this.  This is no different from the requirement when you use it with the syntax:

```
python3 fontname.py [NEW FONT FAMILY NAME] [FONT PATH 1] <FONT PATH ...>
```

If you want a simpler approach that does not involve PATH editing, you can always point the python interpreter at the script location on your system:

```
python3 path/to/directory/fontname.py [NEW FONT FAMILY NAME] [FONT PATH 1] <FONT PATH ...>
```

Let me know if this doesn't address your question.

**Comment by chrissimpkins** [comment]
It is also possible to remove the `.py` file extension from the file if you prefer to use the syntax:

```
fontname [NEW FONT FAMILY NAME] [FONT PATH 1] <FONT PATH ...>
```

**Comment by laictype** [comment]
> If you want a simpler approach that does not involve PATH editing, you can always point the python interpreter at the script location on your system:
>`python3 path/to/directory/fontname.py [NEW FONT FAMILY NAME] [FONT PATH 1] <FONT PATH ...>`

Thank you for describing it so precisely! 
The one quoted above seems like a solution for me. I will examine that.
Best!

**Comment by chrissimpkins** [comment]
Good luck!
